cask_args appdir: '/Applications'

brew 'awscli'
brew 'coreutils'
brew 'direnv'
brew 'docker-compose'
brew 'fish'
brew 'htop'
brew 'jq'
brew 'mas'
brew 'node'
brew 'pgcli'
brew 'python3'
brew 'ripgrep'
brew 'tmux'

cask 'boostnote'
cask 'brave-browser'
cask 'nordvpn'
cask 'slack'
cask 'spectacle'
cask 'visual-studio-code'
cask 'zettlr'
