cask_args appdir: '/Applications'

brew 'awscli'
brew 'coreutils'
brew 'direnv'
brew 'docker-compose'
brew 'fish'
brew 'htop'
brew 'jq'
brew 'languagetool'
brew 'mas'
brew 'mysql-client'
brew 'neovim'
brew 'node'
brew 'pgcli'
brew 'rbenv'
brew 'ripgrep'
brew 'tmux'

cask 'boostnote'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'nordvpn'
cask 'slack'
cask 'spectacle'
cask 'zettlr'

